# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a206ff4a15e556c1d5e5403ebb0344cb92d37049f4a965c0f571955fb9f1c3759644dc8f3c0365fcaa49b4b13ac51676f90e1cf223c8065e0235bfdd0e7b976

test:
  secret_key_base: 3d627c791d899453b77186ba1ff9b23e277d8befdc766d88c4feb140bb8f2ccf4ccc112c2227fcb757662669c099065d9d76d518d4157124c6a22fd3b7ad0db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
